### ISSUE TITLE
Checkout_dir 

### ISSUE THREAD

**Issue by sofiafh** [rdcolema/tensorflow-image-classification#1]
Hey,
Thank you for the notebook.
I wanted to ask you about the checkout_dir ? Don't really understand its purpose .

**Comment by rdcolema** [comment]
Hey sofiafh, are you referring to the `checkpoint_dir` path referenced at the beginning of the notebook? In this case it's not being used, but it's there in case you want to save your model after training or load a trained model from a checkpoint. This is just the directory where you'd store those model checkpoints.

Check out the "Saving and Restoring" section here for more details on saving and loading models: https://www.tensorflow.org/programmers_guide/variables

**Comment by sofiafh** [comment]
Ah okay, get it now. Thank you so much
