### ISSUE TITLE
Issue with reading training set

### ISSUE THREAD

**Issue by rezacsedu** [rdcolema/tensorflow-image-classification#10]
Hi, 

I have downloaded the dataset from Kaggale website and tried to execute the Notebook but in a Python script instead. However, I am experiencing some errors:

root@mohade-ThinkPad-W540:~/ python3 cnn.py
Reading training images
Loading dogs files (Index: 0)
Loading cats files (Index: 1)
0
Reading test images
Size of:
- Training-set:		0
- Test-set:		12500
- Validation-set:	0
no images to show
Traceback (most recent call last):
  File "cnn.py", line 476, in <module>
    optimize(num_iterations=1)
  File "cnn.py", line 305, in optimize
    x_batch, y_true_batch, _, cls_batch = data.train.next_batch(train_batch_size)
  File "dataset.py", line 125, in next_batch
    assert batch_size <= self._num_examples
AssertionError

From the above logs it seems that either these two methods are not reading the training set correctly or I am doing something wrong. Could you please help me on this?

**Comment by ramyalightningfast** [comment]
May i know who is this? 

---- Md. Rezaul Karim wrote ----

**Comment by rdcolema** [comment]
how is your data directory structured? It should be something like `.../data/train/cats/` and `...data/train/dogs/`

**Comment by rezacsedu** [comment]
@rdcolema, that helped. Thanks so much.
