### ISSUE TITLE
I would like to quote your open source in my master thesis.

### ISSUE THREAD

**Issue by kordokrip** [rdcolema/tensorflow-image-classification#11]
I would like to use your source for validation for aerial image classification using the CNN algorithm of my thesis. I am open source, but I will tell my source and developer about my article.

name: Hogil Kang
e-mail: positiveroad@hanmail.net

**Comment by rdcolema** [comment]
Not sure I completely understand what you're requesting, but if you just would like to quote something from the code that's definitely fine with me.

**Comment by momalave** [comment]
The training data is not loading for me. Did you change the format of the cat0.jpg and dog0.jpg images?
