### ISSUE TITLE
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a int64 into a Tensor.

### ISSUE THREAD

**Issue by jaideepc** [rdcolema/tensorflow-image-classification#13]
I am trying to change the code to accommodate 10 classes instead of 2. 
What changes do I have to make in the code to do this?
 I tried running the code with 10 classes and changed this function to this:
def sample_prediction(test_im):
    feed_dict_test = {
        x: test_im.reshape(1, img_size_flat),
        y_true: np.array([[9,8,7,6,5,4,3,2,1,0]])
    }
But, I am still getting an error:
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a int64 into a Tensor.

**Comment by rdcolema** [comment]
Not positive what's causing that, but try using different names for the keys in your feed dict -- see here for context: https://stackoverflow.com/questions/37267584/tensorflow-feed-dict-using-same-symbol-for-key-value-pair-got-typeerror-can
