### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by muhammadhanif1** [rdcolema/tensorflow-image-classification#15]
line 261, in <module> use_pooling=True)

TypeError: 'NoneType' object is not iterable

# Convolutional Layer 1
layer_conv1, weights_conv1 = new_conv_layer(input=x_image,
                   num_input_channels=num_channels,
                   filter_size=filter_size1,
                   num_filters=num_filters1,
                   use_pooling=True) % Here is the error in code...

Please help to solve this problem...

**Comment by rdcolema** [comment]
Hi @muhammadhanif1, can you provide the full traceback? Also it could be a Tensorflow version issue since I wrote this a couple years ago and a lot of their code has changed since then.

**Comment by FajarSukma** [comment]
Hello, can i use this code for multiclassification?

**Comment by rdcolema** [comment]
@FajarSukma yes
