### ISSUE TITLE
TypeError: dst is not a numpy array, neither a scalar on Line 22 of dataset.py

### ISSUE THREAD

**Issue by darshak-bhatti** [rdcolema/tensorflow-image-classification#3]

**Comment by rdcolema** [comment]
Hi,

Need a bit more context than that to help. Could be an OpenCV version mismatch. Try taking a look at these SO answers:

http://stackoverflow.com/questions/34326939/opencv-createcalibratedebevec-process-is-giving-me-dst-is-not-a-numpy-array-ne

http://stackoverflow.com/questions/28536794/exceptions-typeerror-src-is-not-a-numpy-array-neither-a-scalar

**Comment by RiyaSuman** [comment]
Hi... actually I was looking at the image classification code using convolution neural networks...I just wanted to know how many approximate hidden layers might be there in the network
