### ISSUE TITLE
Failed to load dataset

### ISSUE THREAD

**Issue by tapanprakasht** [rdcolema/tensorflow-image-classification#4]
While loading the dataset I am getting the following error. 
```
img = cv2.resize(img, (image_size, image_size), cv2.INTER_LINEAR)
TypeError: dst is not a numpy array, neither a scalar
```
I am using python 2.7  and openCV version 2.4.13.
Could you please check it out?

**Comment by rdcolema** [comment]
Hi Tapan,

Somebody else had a similar error a while back: https://github.com/rdcolema/tensorflow-image-classification/issues/3

Not sure if they were able to resolve using those resources or not, but worth a try before digging in further. 

Let me know if that helps!
