### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by kaushalksharma1989** [rdcolema/tensorflow-image-classification#5]
I exported the notebook script to .py script and running it on Python 2.7. I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cnn.py", line 787, in <module>
    print_validation_accuracy()
  File "cnn.py", line 743, in print_validation_accuracy
    feed_dict = {x: images,
UnboundLocalError: local variable 'x' referenced before assignment

How can I resolve this?

Thanks

**Comment by rdcolema** [comment]
Hi,

Can you take a look at this issue from a few months ago (similar error to the one you described) and see if that helps? https://github.com/rdcolema/tensorflow-image-classification/issues/2

Thanks,
RC

**Comment by kaushalksharma1989** [comment]
Yeah. I was just going through the past issues and adopted the same resolution. Thanks :)
