### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by trinitron83** [rdcolema/tensorflow-image-classification#7]
It would be great to see an addition where you show how to use the model on new images once it's trained!

**Comment by rdcolema** [comment]
Hey Brian,

Thanks for the feedback -- I'll add in an example soon and will post here once it's updated. 

-RC

**Comment by rdcolema** [comment]
https://github.com/rdcolema/tensorflow-image-classification/blob/master/cnn.ipynb

^^ updated with examples of how to make predictions on new images

**Comment by trinitron83** [comment]
Wow, that's great! In the meantime I actually pieced together how to do it myself, but I'm sure someone will find it helpful!!
