### ISSUE TITLE
ValueError: cannot reshape array of size 786432 into shape (32,49152)

### ISSUE THREAD

**Issue by DeepStillWater** [rdcolema/tensorflow-image-classification#8]
Hi,I'm using your code to train another datasets and I get the following errors:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-ad470030e9e7> in <module>()
----> 1 print_validation_accuracy(show_example_errors=True)

<ipython-input-51-4d8b77a113ed> in print_validation_accuracy(show_example_errors, show_confusion_matrix)
     22 
     23         # Get the images from the test-set between index i and j.
---> 24         images = data.valid.images[i:j, :].reshape(batch_size, img_size_flat)
     25 
     26 

ValueError: cannot reshape array of size 786432 into shape (32,49152)

My picture size is 300x300 and I just changed the calsses,what should I do?

There are my numbers of datasets

Size of:
- Training-set:		6972
- Test-set:		10593
- Validation-set:	1328

**Comment by rdcolema** [comment]
Hi, haven't had time to look at this in-depth but my first guess is that it's related to the number of validation images not being divisible by the batch size. If that's the case you should be able to fix that either by changing the batch size or the number of validation images. 

You also might be able to rewrite parts of `dataset.py` to make the script more flexible with regards to this.

If that isn't the issue let me know and I'll take a closer look.

-RC

**Comment by Samuel-Lo** [comment]
I have same problem too.
I revise it into `images = data.valid.images[i:j, :].reshape(-1,img_size_flat)`
It works for me
